name: Run Xircuits Workflows Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: "*"

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    env:
      EXCLUDED_XIRCIRCUITS: "path/to/excluded1.xircuits path/to/excluded2.xircuits"
      # Uncomment the following line and specify paths to exclude additional .xircuits files
      # EXCLUDED_XIRCIRCUITS: "path/to/excluded1.xircuits path/to/excluded2.xircuits path/to/another_excluded.xircuits"

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set COMPONENT_LIBRARY_PATH
      run: |
        REPO_NAME="${GITHUB_REPOSITORY##*/}"
        COMPONENT_LIBRARY_PATH=$(echo "xai_components/xai_${REPO_NAME}" | sed 's/-/_/g')
        echo "COMPONENT_LIBRARY_PATH=$COMPONENT_LIBRARY_PATH" >> $GITHUB_ENV

    - name: Install xircuits
      run: pip install xircuits

    - name: List xircuits
      run: xircuits list

    - name: Clone Repository
      run: git clone https://github.com/${{ github.repository }} ${{ env.COMPONENT_LIBRARY_PATH }}

    - name: Process .xircuits Files
      run: |
        cd ${{ env.COMPONENT_LIBRARY_PATH }}
        FILES=$(find . -name "*.xircuits")
        for file in $FILES; do
          if [[ $EXCLUDED_XIRCIRCUITS != *"$file"* ]]; then
            xircuits compile $file
            python "${file%.*}.py"
          fi
        done